export type Card = {
  id: string;
  name: string;
  code: string;
  set: string;
  qty: number;
  language: string;
  condition: string;
  buyPrice: number | null;
  pricePaid?: number | null;
  pokedexNumber: number;
  type1: string;
  type2: string | null;
  generation: number;
  variant: string | null;
  owned: boolean;
};

export const cards: Card[] = [
  { id: "abra", name: "Abra", code: "sv2a 063", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 63, type1: "Psychic", type2: null, generation: 1, variant: null, owned: false },
  { id: "aerodactyl", name: "Aerodactyl", code: "sv2a 142", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 142, type1: "Rock", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "alakazam", name: "Alakazam", code: "m1S 071", set: "Mega Symphonia", qty: 1, language: "Japanese", condition: "NM", buyPrice: 4.00, pokedexNumber: 65, type1: "Psychic", type2: null, generation: 1, variant: null, owned: false },
  { id: "alolan-dugtrio", name: "Alolan Dugtrio", code: "sv8 116", set: "Super Electric Breaker", qty: 1, language: "Japanese", condition: "NM", buyPrice: 1.50, pokedexNumber: 51, type1: "Ground", type2: "Steel", generation: 1, variant: "Alolan Form", owned: false },
  { id: "alolan-golem-gx", name: "Alolan Golem GX", code: "sm4s 051", set: "Awakened Heroes", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pokedexNumber: 76, type1: "Rock", type2: "Electric", generation: 1, variant: "Alolan Form / GX", owned: false },
  { id: "arbok", name: "Arbok", code: "sv5K 079", set: "Wild Force", qty: 1, language: "Japanese", condition: "NM", buyPrice: 3.50, pricePaid: 3.45, pokedexNumber: 24, type1: "Poison", type2: null, generation: 1, variant: null, owned: true },
  { id: "articuno", name: "Articuno", code: "sv9 102", set: "Battle Partners", qty: 1, language: "Japanese", condition: "NM", buyPrice: 8.00, pokedexNumber: 144, type1: "Ice", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "beedrill-v", name: "Beedrill V", code: "s10P 069", set: "Space Juggler", qty: 1, language: "Japanese", condition: "NM", buyPrice: 40.00, pokedexNumber: 15, type1: "Bug", type2: "Poison", generation: 1, variant: "V", owned: false },
  { id: "bellsprout", name: "Bellsprout", code: "sv2a 069", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 69, type1: "Grass", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "blastoise-ex", name: "Blastoise ex", code: "sv2a 202", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 135.00, pokedexNumber: 9, type1: "Water", type2: null, generation: 1, variant: "ex", owned: false },
  { id: "bulbasaur", name: "Bulbasaur", code: "m1L 064", set: "Mega Brave", qty: 1, language: "Japanese", condition: "NM", buyPrice: 9.00, pricePaid: 7.94, pokedexNumber: 1, type1: "Grass", type2: "Poison", generation: 1, variant: null, owned: true },
  { id: "butterfree-vmax", name: "Butterfree VMAX", code: "S2A 79", set: "Explosive Flame Walker", qty: 1, language: "Japanese", condition: "NM", buyPrice: 20.00, pokedexNumber: 12, type1: "Bug", type2: "Flying", generation: 1, variant: "VMAX", owned: false },
  { id: "caterpie", name: "Caterpie", code: "sv2a 172", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 3.50, pokedexNumber: 10, type1: "Bug", type2: null, generation: 1, variant: null, owned: false },
  { id: "chansey", name: "Chansey", code: "sv6 113", set: "Mask of Change", qty: 1, language: "Japanese", condition: "NM", buyPrice: 15.00, pokedexNumber: 113, type1: "Normal", type2: null, generation: 1, variant: null, owned: false },
  { id: "charizard", name: "Charizard", code: "s8b 187", set: "VMAX Climax", qty: 1, language: "Japanese", condition: "NM", buyPrice: 15.00, pricePaid: 14.95, pokedexNumber: 6, type1: "Fire", type2: "Flying", generation: 1, variant: null, owned: true },
  { id: "charmander", name: "Charmander", code: "sv2a 168", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 20.00, pokedexNumber: 4, type1: "Fire", type2: null, generation: 1, variant: null, owned: false },
  { id: "charmeleon", name: "Charmeleon", code: "sv2a 169", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 15.00, pokedexNumber: 5, type1: "Fire", type2: null, generation: 1, variant: null, owned: false },
  { id: "clefairy", name: "Clefairy", code: "m3 086", set: "Nihil Zero", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pokedexNumber: 35, type1: "Fairy", type2: null, generation: 1, variant: null, owned: false },
  { id: "cloyster", name: "Cloyster", code: "sv2a 091", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 91, type1: "Water", type2: "Ice", generation: 1, variant: null, owned: false },
  { id: "cubone", name: "Cubone", code: "sv2a 104", set: "Pokemon Card 151", qty: 1, language: "Any", condition: "NM", buyPrice: null, pokedexNumber: 104, type1: "Ground", type2: null, generation: 1, variant: null, owned: false },
  { id: "dewgong", name: "Dewgong", code: "m2 084", set: "Inferno X", qty: 1, language: "Japanese", condition: "NM", buyPrice: 2.00, pokedexNumber: 87, type1: "Water", type2: "Ice", generation: 1, variant: null, owned: false },
  { id: "diglett", name: "Diglett", code: "sv2a 050", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 50, type1: "Ground", type2: null, generation: 1, variant: null, owned: false },
  { id: "ditto", name: "Ditto", code: "s12a 197", set: "VSTAR Universe", qty: 1, language: "Japanese", condition: "NM", buyPrice: 4.00, pokedexNumber: 132, type1: "Normal", type2: null, generation: 1, variant: null, owned: false },
  { id: "dodrio", name: "Dodrio", code: "sv2a 085", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 85, type1: "Normal", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "doduo", name: "Doduo", code: "sv2a 084", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 84, type1: "Normal", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "dragonair", name: "Dragonair", code: "sv2a 182", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pokedexNumber: 148, type1: "Dragon", type2: null, generation: 1, variant: null, owned: false },
  { id: "dratini", name: "Dratini", code: "sv2a 147", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 147, type1: "Dragon", type2: null, generation: 1, variant: null, owned: false },
  { id: "drowzee", name: "Drowzee", code: "sv1V 086", set: "Violet ex", qty: 1, language: "Japanese", condition: "NM", buyPrice: 12.00, pokedexNumber: 96, type1: "Psychic", type2: null, generation: 1, variant: null, owned: false },
  { id: "eevee", name: "Eevee", code: "sv5a 078", set: "Crimson Haze", qty: 1, language: "Japanese", condition: "NM", buyPrice: 25.00, pokedexNumber: 133, type1: "Normal", type2: null, generation: 1, variant: null, owned: false },
  { id: "ekans", name: "Ekans Lv.16", code: "DP4d", set: "Dawn Dash", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 23, type1: "Poison", type2: null, generation: 1, variant: null, owned: false },
  { id: "electabuzz", name: "Electabuzz", code: "sv2a 125", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 125, type1: "Electric", type2: null, generation: 1, variant: null, owned: false },
  { id: "electrode", name: "Electrode", code: "sv2a 101", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 101, type1: "Electric", type2: null, generation: 1, variant: null, owned: false },
  { id: "exeggcute", name: "Exeggcute", code: "sv7a 065", set: "Paradise Dragona", qty: 1, language: "Japanese", condition: "NM", buyPrice: 2.00, pokedexNumber: 102, type1: "Grass", type2: "Psychic", generation: 1, variant: null, owned: false },
  { id: "exeggutor", name: "Exeggutor", code: "m1L 066", set: "Mega Brave", qty: 1, language: "Japanese", condition: "NM", buyPrice: 2.00, pokedexNumber: 103, type1: "Grass", type2: "Psychic", generation: 1, variant: null, owned: false },
  { id: "farfetchd", name: "Farfetch'd", code: "sv2a 083", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 83, type1: "Normal", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "fearow", name: "Fearow", code: "sv2a 022", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 22, type1: "Normal", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "flareon", name: "Flareon", code: "s8b 188", set: "VMAX Climax", qty: 1, language: "Japanese", condition: "NM", buyPrice: 12.00, pokedexNumber: 136, type1: "Fire", type2: null, generation: 1, variant: null, owned: false },
  { id: "galarian-articuno", name: "Galarian Articuno", code: "s12a 182", set: "VSTAR Universe", qty: 1, language: "Japanese", condition: "NM", buyPrice: 3.00, pokedexNumber: 144, type1: "Psychic", type2: "Flying", generation: 1, variant: "Galarian Form", owned: false },
  { id: "galarian-moltres", name: "Galarian Moltres", code: "s12a 190", set: "VSTAR Universe", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pokedexNumber: 146, type1: "Dark", type2: "Flying", generation: 1, variant: "Galarian Form", owned: false },
  { id: "galarian-zapdos", name: "Galarian Zapdos", code: "s12a 188", set: "VSTAR Universe", qty: 1, language: "Japanese", condition: "NM", buyPrice: 2.00, pokedexNumber: 145, type1: "Fighting", type2: "Flying", generation: 1, variant: "Galarian Form", owned: false },
  { id: "gastly", name: "Gastly", code: "sv5K 080", set: "Wild Force", qty: 1, language: "Japanese", condition: "NM", buyPrice: 22.00, pokedexNumber: 92, type1: "Ghost", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "gengar", name: "Gengar", code: "s10a 074", set: "Dark Phantasma", qty: 1, language: "Japanese", condition: "NM", buyPrice: 24.00, pokedexNumber: 94, type1: "Ghost", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "geodude", name: "Geodude", code: "sv2a 074", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 74, type1: "Rock", type2: "Ground", generation: 1, variant: null, owned: false },
  { id: "gloom", name: "Gloom", code: "sv3 109", set: "Ruler of the Black Flame", qty: 1, language: "Japanese", condition: "NM", buyPrice: 4.00, pokedexNumber: 44, type1: "Grass", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "golbat", name: "Golbat", code: "sv2a 042", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 42, type1: "Poison", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "goldeen", name: "Goldeen", code: "sv2a 118", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 118, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "golduck", name: "Golduck", code: "sv2a 055", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 55, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "graveler", name: "Graveler", code: "sv2a 075", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 75, type1: "Rock", type2: "Ground", generation: 1, variant: null, owned: false },
  { id: "grimer", name: "Grimer", code: "sv2a 088", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 88, type1: "Poison", type2: null, generation: 1, variant: null, owned: false },
  { id: "gyarados-ex", name: "Gyarados ex", code: "sv1S 091", set: "Scarlet ex", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pokedexNumber: 130, type1: "Water", type2: "Flying", generation: 1, variant: "ex", owned: false },
  { id: "haunter", name: "Haunter", code: "mBG 022", set: "MEGA Starter Set Mega Gengar ex", qty: 1, language: "Japanese", condition: "NM", buyPrice: 25.00, pokedexNumber: 93, type1: "Ghost", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "hisuian-arcanine", name: "Hisuian Arcanine", code: "s10a 075", set: "Dark Phantasma", qty: 1, language: "Japanese", condition: "NM", buyPrice: 2.00, pokedexNumber: 59, type1: "Fire", type2: "Rock", generation: 1, variant: "Hisuian Form", owned: false },
  { id: "hisuian-growlithe", name: "Hisuian Growlithe", code: "sv5a 075", set: "Crimson Haze", qty: 1, language: "Japanese", condition: "NM", buyPrice: 5.00, pokedexNumber: 58, type1: "Fire", type2: "Rock", generation: 1, variant: "Hisuian Form", owned: false },
  { id: "hisuian-voltorb", name: "Hisuian Voltorb", code: "s12a 173", set: "VSTAR Universe", qty: 1, language: "Japanese", condition: "NM", buyPrice: 1.25, pokedexNumber: 100, type1: "Electric", type2: "Grass", generation: 1, variant: "Hisuian Form", owned: false },
  { id: "hitmonchan", name: "Hitmonchan", code: "sv2a 107", set: "Pokemon Card 151", qty: 1, language: "Any", condition: "NM", buyPrice: null, pokedexNumber: 107, type1: "Fighting", type2: null, generation: 1, variant: null, owned: false },
  { id: "hitmonlee", name: "Hitmonlee", code: "sv2a 106", set: "Pokemon Card 151", qty: 1, language: "Any", condition: "NM", buyPrice: null, pokedexNumber: 106, type1: "Fighting", type2: null, generation: 1, variant: null, owned: false },
  { id: "horsea", name: "Horsea", code: "sv6a 067", set: "Night Wanderer", qty: 1, language: "Japanese", condition: "NM", buyPrice: 6.00, pokedexNumber: 116, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "hypno", name: "Hypno", code: "sv2a 097", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 97, type1: "Psychic", type2: null, generation: 1, variant: null, owned: false },
  { id: "ivysaur", name: "Ivysaur", code: "m1L 065", set: "Mega Brave", qty: 1, language: "Japanese", condition: "NM", buyPrice: 5.00, pricePaid: 4.89, pokedexNumber: 2, type1: "Grass", type2: "Poison", generation: 1, variant: null, owned: true },
  { id: "jigglypuff", name: "Jigglypuff", code: "sv2a 039", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 39, type1: "Normal", type2: "Fairy", generation: 1, variant: null, owned: false },
  { id: "jolteon", name: "Jolteon", code: "s8b 193", set: "VMAX Climax", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pokedexNumber: 135, type1: "Electric", type2: null, generation: 1, variant: null, owned: false },
  { id: "jynx", name: "Jynx", code: "s11a 071", set: "Incandescent Arcana", qty: 1, language: "Japanese", condition: "NM", buyPrice: 2.00, pokedexNumber: 124, type1: "Ice", type2: "Psychic", generation: 1, variant: null, owned: false },
  { id: "kabuto", name: "Kabuto", code: "sv2a 140", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 140, type1: "Rock", type2: "Water", generation: 1, variant: null, owned: false },
  { id: "kabutops", name: "Kabutops", code: "sv2a 141", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 141, type1: "Rock", type2: "Water", generation: 1, variant: null, owned: false },
  { id: "kadabra", name: "Kadabra", code: "sv2a 064", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 64, type1: "Psychic", type2: null, generation: 1, variant: null, owned: false },
  { id: "kakuna", name: "Kakuna", code: "sv2a 014", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 14, type1: "Bug", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "kangaskhan", name: "Kangaskhan", code: "sv10 110", set: "The Glory of Team Rocket", qty: 1, language: "Japanese", condition: "NM", buyPrice: 3.00, pokedexNumber: 115, type1: "Normal", type2: null, generation: 1, variant: null, owned: false },
  { id: "kingler", name: "Kingler", code: "sv2a 099", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 99, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "koffing", name: "Koffing", code: "sm11b 056", set: "Dream League", qty: 1, language: "Any", condition: "NM", buyPrice: 22.00, pokedexNumber: 109, type1: "Poison", type2: null, generation: 1, variant: null, owned: false },
  { id: "krabby", name: "Krabby", code: "sv2a 098", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 98, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "lapras", name: "Lapras", code: "s12a 177", set: "VSTAR Universe", qty: 1, language: "Japanese", condition: "NM", buyPrice: 5.00, pokedexNumber: 131, type1: "Water", type2: "Ice", generation: 1, variant: null, owned: false },
  { id: "lickitung", name: "Lickitung", code: "sv5M 082", set: "Cyber Judge", qty: 1, language: "Any", condition: "NM", buyPrice: 5.00, pokedexNumber: 108, type1: "Normal", type2: null, generation: 1, variant: null, owned: false },
  { id: "machamp", name: "Machamp", code: "sv2a 068", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 68, type1: "Fighting", type2: null, generation: 1, variant: null, owned: false },
  { id: "machoke", name: "Machoke", code: "sv2a 177", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 4.00, pokedexNumber: 67, type1: "Fighting", type2: null, generation: 1, variant: null, owned: false },
  { id: "machop", name: "Machop", code: "sv2a 066", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 66, type1: "Fighting", type2: null, generation: 1, variant: null, owned: false },
  { id: "magikarp", name: "Magikarp", code: "sv2a 129", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 129, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "magmar", name: "Magmar", code: "sv2a 126", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 126, type1: "Fire", type2: null, generation: 1, variant: null, owned: false },
  { id: "magnemite", name: "Magnemite", code: "sm11b 055", set: "Dream League", qty: 1, language: "Japanese", condition: "NM", buyPrice: 15.00, pokedexNumber: 81, type1: "Electric", type2: "Steel", generation: 1, variant: null, owned: false },
  { id: "magneton", name: "Magneton", code: "sv8 112", set: "Super Electric Breaker", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pokedexNumber: 82, type1: "Electric", type2: "Steel", generation: 1, variant: null, owned: false },
  { id: "mankey", name: "Mankey", code: "sv2a 056", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 56, type1: "Fighting", type2: null, generation: 1, variant: null, owned: false },
  { id: "marowak", name: "Marowak", code: "sv2a 105", set: "Pokemon Card 151", qty: 1, language: "Any", condition: "NM", buyPrice: null, pokedexNumber: 105, type1: "Ground", type2: null, generation: 1, variant: null, owned: false },
  { id: "mega-clefable-ex", name: "Mega Clefable ex", code: "m3 112", set: "Nihil Zero", qty: 1, language: "Japanese", condition: "NM", buyPrice: 30.00, pokedexNumber: 36, type1: "Fairy", type2: null, generation: 1, variant: "Mega / ex", owned: false },
  { id: "mega-dragonite-ex", name: "Mega Dragonite ex", code: "m2a 232", set: "MEGA Dream ex", qty: 1, language: "Japanese", condition: "NM", buyPrice: 12.00, pokedexNumber: 149, type1: "Dragon", type2: "Flying", generation: 1, variant: "Mega / ex", owned: false },
  { id: "meowth", name: "Meowth", code: "SV-P 192", set: "Scarlet & Violet Promos", qty: 1, language: "Japanese", condition: "NM", buyPrice: 60.00, pokedexNumber: 52, type1: "Normal", type2: null, generation: 1, variant: null, owned: false },
  { id: "metapod", name: "Metapod", code: "sv9 002", set: "Battle Partners", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 11, type1: "Bug", type2: null, generation: 1, variant: null, owned: false },
  { id: "mew-v", name: "Mew V", code: "s12a 183", set: "VSTAR Universe", qty: 1, language: "Japanese", condition: "NM", buyPrice: 30.00, pokedexNumber: 151, type1: "Psychic", type2: null, generation: 1, variant: "V", owned: false },
  { id: "mewtwo", name: "Mewtwo", code: "sv2a 183", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 20.00, pokedexNumber: 150, type1: "Psychic", type2: null, generation: 1, variant: null, owned: false },
  { id: "mistys-lapras", name: "Misty's Lapras", code: "sv9a 072", set: "Heat Wave Arena", qty: 1, language: "Japanese", condition: "NM", buyPrice: 12.00, pokedexNumber: 131, type1: "Water", type2: "Ice", generation: 1, variant: "Trainer's Pokemon", owned: false },
  { id: "mistys-psyduck", name: "Misty's Psyduck", code: "sv9a 071", set: "Heat Wave Arena", qty: 1, language: "Japanese", condition: "NM", buyPrice: 25.00, pokedexNumber: 54, type1: "Water", type2: null, generation: 1, variant: "Trainer's Pokemon", owned: false },
  { id: "mr-mime", name: "Mr. Mime", code: "sv2a 179", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 2.00, pokedexNumber: 122, type1: "Psychic", type2: "Fairy", generation: 1, variant: null, owned: false },
  { id: "muk", name: "Muk", code: "sv2a 089", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 89, type1: "Poison", type2: null, generation: 1, variant: null, owned: false },
  { id: "nidoking", name: "Nidoking", code: "sv2a 174", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 5.00, pokedexNumber: 34, type1: "Poison", type2: "Ground", generation: 1, variant: null, owned: false },
  { id: "nidoqueen", name: "Nidoqueen", code: "sv2a 031", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 31, type1: "Poison", type2: "Ground", generation: 1, variant: null, owned: false },
  { id: "nidoran-f", name: "Nidoran F", code: "sv2a 029", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 29, type1: "Poison", type2: null, generation: 1, variant: null, owned: false },
  { id: "nidoran-m", name: "Nidoran M", code: "sv2a 032", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 32, type1: "Poison", type2: null, generation: 1, variant: null, owned: false },
  { id: "nidorina", name: "Nidorina", code: "sv2a 030", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 30, type1: "Poison", type2: null, generation: 1, variant: null, owned: false },
  { id: "nidorino", name: "Nidorino", code: "sv2a 033", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 33, type1: "Poison", type2: null, generation: 1, variant: null, owned: false },
  { id: "ninetales", name: "Ninetales", code: "sv3 110", set: "Ruler of the Black Flame", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pricePaid: 9.89, pokedexNumber: 38, type1: "Fire", type2: null, generation: 1, variant: null, owned: true },
  { id: "oddish", name: "Oddish", code: "sv2a 043", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 43, type1: "Grass", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "omanyte", name: "Omanyte", code: "sv2a 180", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 3.00, pokedexNumber: 138, type1: "Rock", type2: "Water", generation: 1, variant: null, owned: false },
  { id: "omastar", name: "Omastar", code: "sv2a 139", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 139, type1: "Rock", type2: "Water", generation: 1, variant: null, owned: false },
  { id: "onix", name: "Onix", code: "sv2a 095", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 95, type1: "Rock", type2: "Ground", generation: 1, variant: null, owned: false },
  { id: "paldean-tauros", name: "Paldean Tauros", code: "sv1a 084", set: "Triplet Beat", qty: 1, language: "Japanese", condition: "NM", buyPrice: 3.00, pokedexNumber: 128, type1: "Fighting", type2: null, generation: 1, variant: "Paldean Form", owned: false },
  { id: "paras", name: "Paras", code: "s12a 207", set: "VSTAR Universe", qty: 1, language: "Japanese", condition: "NM", buyPrice: 20.00, pokedexNumber: 46, type1: "Bug", type2: "Grass", generation: 1, variant: null, owned: false },
  { id: "parasect", name: "Parasect", code: "s10a 072", set: "Dark Phantasma", qty: 1, language: "Japanese", condition: "NM", buyPrice: 1.50, pokedexNumber: 47, type1: "Bug", type2: "Grass", generation: 1, variant: null, owned: false },
  { id: "persian", name: "Persian", code: "sv6a 075", set: "Night Wanderer", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pricePaid: 8.48, pokedexNumber: 53, type1: "Normal", type2: null, generation: 1, variant: null, owned: true },
  { id: "pidgeot-ex", name: "Pidgeot ex", code: "sv3 136", set: "Ruler of the Black Flame", qty: 1, language: "Japanese", condition: "NM", buyPrice: 22.00, pokedexNumber: 18, type1: "Normal", type2: "Flying", generation: 1, variant: "ex", owned: false },
  { id: "pidgeotto", name: "Pidgeotto", code: "sv3 119", set: "Ruler of the Black Flame", qty: 1, language: "Japanese", condition: "NM", buyPrice: 2.50, pokedexNumber: 17, type1: "Normal", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "pidgey", name: "Pidgey", code: "sv3 118", set: "Ruler of the Black Flame", qty: 1, language: "Japanese", condition: "NM", buyPrice: 4.00, pokedexNumber: 16, type1: "Normal", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "pikachu", name: "Pikachu", code: "s10a 073", set: "Dark Phantasma", qty: 1, language: "Japanese", condition: "NM", buyPrice: 40.00, pokedexNumber: 25, type1: "Electric", type2: null, generation: 1, variant: null, owned: false },
  { id: "pinsir", name: "Pinsir", code: "sv5a 067", set: "Crimson Haze", qty: 1, language: "Japanese", condition: "NM", buyPrice: 4.00, pokedexNumber: 127, type1: "Bug", type2: null, generation: 1, variant: null, owned: false },
  { id: "poliwag", name: "Poliwag", code: "sv2a 060", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 60, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "poliwhirl", name: "Poliwhirl", code: "sv2a 176", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pokedexNumber: 61, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "poliwrath", name: "Poliwrath", code: "sv2a 062", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 62, type1: "Water", type2: "Fighting", generation: 1, variant: null, owned: false },
  { id: "ponyta", name: "Ponyta", code: "sv2a 077", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 77, type1: "Fire", type2: null, generation: 1, variant: null, owned: false },
  { id: "porygon", name: "Porygon", code: "sv2a 137", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 137, type1: "Normal", type2: null, generation: 1, variant: null, owned: false },
  { id: "primeape", name: "Primeape", code: "sv2a 057", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 57, type1: "Fighting", type2: null, generation: 1, variant: null, owned: false },
  { id: "raichu", name: "Raichu", code: "sv2D 074", set: "Clay Burst", qty: 1, language: "Japanese", condition: "NM", buyPrice: 14.00, pokedexNumber: 26, type1: "Electric", type2: null, generation: 1, variant: null, owned: false },
  { id: "rapidash", name: "Rapidash", code: "sv9a 069", set: "Heat Wave Arena", qty: 1, language: "Japanese", condition: "NM", buyPrice: 3.00, pokedexNumber: 78, type1: "Fire", type2: null, generation: 1, variant: null, owned: false },
  { id: "raticate", name: "Raticate", code: "m3 092", set: "Nihil Zero", qty: 1, language: "Japanese", condition: "NM", buyPrice: 2.50, pricePaid: 2.25, pokedexNumber: 20, type1: "Normal", type2: null, generation: 1, variant: null, owned: true },
  { id: "rattata", name: "Rattata", code: "m3 059", set: "Nihil Zero", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 19, type1: "Normal", type2: null, generation: 1, variant: null, owned: false },
  { id: "rhydon", name: "Rhydon", code: "sv2a 112", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 112, type1: "Ground", type2: "Rock", generation: 1, variant: null, owned: false },
  { id: "rhyhorn", name: "Rhyhorn", code: "sv2a 111", set: "Pokemon Card 151", qty: 1, language: "Any", condition: "NM", buyPrice: null, pokedexNumber: 111, type1: "Ground", type2: "Rock", generation: 1, variant: null, owned: false },
  { id: "sandshrew", name: "Sandshrew", code: "m1L 020", set: "Mega Brave", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 27, type1: "Ground", type2: null, generation: 1, variant: null, owned: false },
  { id: "sandslash", name: "Sandslash", code: "m1L 021", set: "Mega Brave", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 28, type1: "Ground", type2: null, generation: 1, variant: null, owned: false },
  { id: "scyther", name: "Scyther", code: "sv2a 123", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 123, type1: "Bug", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "seadra", name: "Seadra", code: "sv2a 117", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 117, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "seaking", name: "Seaking", code: "sv2a 119", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 119, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "seel", name: "Seel", code: "sv2a 086", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 86, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "shellder", name: "Shellder", code: "sv2a 090", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 90, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "slowbro", name: "Slowbro", code: "sv2a 080", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 80, type1: "Water", type2: "Psychic", generation: 1, variant: null, owned: false },
  { id: "slowpoke", name: "Slowpoke", code: "sv1V 082", set: "Violet ex", qty: 1, language: "Japanese", condition: "NM", buyPrice: 9.00, pokedexNumber: 79, type1: "Water", type2: "Psychic", generation: 1, variant: null, owned: false },
  { id: "snorlax", name: "Snorlax", code: "sv2a 181", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pokedexNumber: 143, type1: "Normal", type2: null, generation: 1, variant: null, owned: false },
  { id: "spearow", name: "Spearow", code: "m1L 074", set: "Mega Brave", qty: 1, language: "Japanese", condition: "NM", buyPrice: 1.00, pokedexNumber: 21, type1: "Normal", type2: "Flying", generation: 1, variant: null, owned: false },
  { id: "squirtle", name: "Squirtle", code: "sv2a 170", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 20.00, pokedexNumber: 7, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "starmie", name: "Starmie", code: "sv2a 121", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 121, type1: "Water", type2: "Psychic", generation: 1, variant: null, owned: false },
  { id: "staryu", name: "Staryu", code: "sv2a 120", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 120, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "tangela", name: "Tangela", code: "sv2a 178", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 3.00, pokedexNumber: 114, type1: "Grass", type2: null, generation: 1, variant: null, owned: false },
  { id: "team-rockets-weezing", name: "Team Rocket's Weezing", code: "sv10 105", set: "The Glory of Team Rocket", qty: 1, language: "Any", condition: "NM", buyPrice: 3.00, pokedexNumber: 110, type1: "Poison", type2: null, generation: 1, variant: "Trainer's Pokemon", owned: false },
  { id: "tentacool", name: "Tentacool", code: "sv2a 072", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 72, type1: "Water", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "tentacruel", name: "Tentacruel", code: "sv2a 073", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 73, type1: "Water", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "vaporeon", name: "Vaporeon", code: "s8b 189", set: "VMAX Climax", qty: 1, language: "Japanese", condition: "NM", buyPrice: 10.00, pokedexNumber: 134, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "venomoth", name: "Venomoth", code: "sv2a 049", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 49, type1: "Bug", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "venonat", name: "Venonat", code: "sv2a 048", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 48, type1: "Bug", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "venusaur-ex", name: "Venusaur ex", code: "sv2a 184", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 9.00, pokedexNumber: 3, type1: "Grass", type2: "Poison", generation: 1, variant: "ex", owned: false },
  { id: "victreebel", name: "Victreebel", code: "sv2a 071", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 71, type1: "Grass", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "vileplume-gx", name: "Vileplume GX", code: "sm11b 062", set: "Dream League", qty: 1, language: "Japanese", condition: "NM", buyPrice: 50.00, pokedexNumber: 45, type1: "Grass", type2: "Poison", generation: 1, variant: "GX", owned: false },
  { id: "vulpix", name: "Vulpix", code: "m1L 067", set: "Mega Brave", qty: 1, language: "Japanese", condition: "NM", buyPrice: 4.00, pricePaid: 3.49, pokedexNumber: 37, type1: "Fire", type2: null, generation: 1, variant: null, owned: true },
  { id: "wartortle", name: "Wartortle", code: "sv2a 171", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: 12.00, pokedexNumber: 8, type1: "Water", type2: null, generation: 1, variant: null, owned: false },
  { id: "weedle", name: "Weedle", code: "sv2a 013", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 13, type1: "Bug", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "weepinbell", name: "Weepinbell", code: "sv2a 070", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 70, type1: "Grass", type2: "Poison", generation: 1, variant: null, owned: false },
  { id: "wigglytuff", name: "Wigglytuff", code: "m2 091", set: "Inferno X", qty: 1, language: "Japanese", condition: "NM", buyPrice: 2.00, pokedexNumber: 40, type1: "Normal", type2: "Fairy", generation: 1, variant: null, owned: false },
  { id: "zubat", name: "Zubat", code: "sv2a 041", set: "Pokemon Card 151", qty: 1, language: "Japanese", condition: "NM", buyPrice: null, pokedexNumber: 41, type1: "Poison", type2: "Flying", generation: 1, variant: null, owned: false },
];

export const typeColors: Record<string, string> = {
  Normal: "#A8A878",
  Fire: "#F08030",
  Water: "#6890F0",
  Electric: "#F8D030",
  Grass: "#78C850",
  Ice: "#98D8D8",
  Fighting: "#C03028",
  Poison: "#A040A0",
  Ground: "#E0C068",
  Flying: "#A890F0",
  Psychic: "#F85888",
  Bug: "#A8B820",
  Rock: "#B8A038",
  Ghost: "#705898",
  Dragon: "#7038F8",
  Dark: "#705848",
  Steel: "#B8B8D0",
  Fairy: "#EE99AC",
};
